### ISSUE TITLE
Littlesis-rails issue !

### ISSUE THREAD

**Issue by domguard** [public-accountability/oligrapher#134]
Hello
sorry to bother you here
As there is no issue manager for the littlesis repo, i'm posting this here
I followed the developer document to install through docker, I'm on debian 12 (testing)
Everything runs smooth except in the end
http://localhost:8080 (or 8081) gives me an error about db migrations :+1: 

```

ActiveRecord::PendingMigrationError
Migrations are pending. To resolve this issue, run:
bin/rails db:migrate RAILS_ENV=development
You have 197 pending migrations:
20180117165745_change_int_length_for_address_category.rb
20180117190400_add_index_on_created_at_to_versions.rb
20180122192339_create_government_advisory_and_research_institute_enity_extensions.rb
20180123184642_add_new_fields_to_business.rb
20180123192048_create_cmp_entities.rb
```

(follow 197 migrations)

If i run a shell to try the migration, I get

```
bin/rails db:migrate RAILS_ENV=development
== 20180117165745 ChangeIntLengthForAddressCategory: migrating ================
-- remove_foreign_key(:address, :address_category)
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Table 'address' has no foreign key for address_category
/littlesis/db/migrate/20180117165745_change_int_length_for_address_category.rb:3:in 'change'

Caused by:
ArgumentError: Table 'address' has no foreign key for address_category
/littlesis/db/migrate/20180117165745_change_int_length_for_address_category.rb:3:in 'change'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

```

I'd like to setup a local littlesis version to work offline 
and perhaps, one day, help others with your tool

**Comment by aepyornis** [comment]
try `db:schema:load` or `db:reset` instead of running the migratations

**Comment by domguard** [comment]
Here's what I get 

```
root@aeadaa44e7ac:/littlesis# bin/rails db:schema:load
psql:/littlesis/db/structure.sql:548: ERROR:  relation "ar_internal_metadata" already exists
rails aborted!
failed to execute:
psql --set ON_ERROR_STOP=1 --quiet --no-psqlrc --output /dev/null --file /littlesis/db/structure.sql littlesis

Please check the output above for any errors and make sure that `psql` is installed in your PATH and has proper permissions.
Tasks: TOP => db:schema:load
(See full trace by running task with --trace)
```
and

```
root@aeadaa44e7ac:/littlesis# bin/rails db:reset
PG::InsufficientPrivilege: ERROR:  must be owner of database littlesis
Couldn't drop database 'littlesis'
rails aborted!
ActiveRecord::StatementInvalid: PG::InsufficientPrivilege: ERROR:  must be owner of database littlesis


Caused by:
PG::InsufficientPrivilege: ERROR:  must be owner of database littlesis

Tasks: TOP => db:drop:_unsafe
(See full trace by running task with --trace)
```

Does this mean owner in the linux sense or another pgsql sense ?


```
root@aeadaa44e7ac:/littlesis# ls -la /littlesis/db/
total 276
drwxr-xr-x  6 1000 1000   4096 Apr 15 17:41 .
drwxr-xr-x 16 1000 1000   4096 Apr 15 14:56 ..
drwxr-xr-x  2 1000 1000  12288 Apr 15 13:16 archived_migrations
drwxr-xr-x  2 1000 1000  20480 Apr 15 13:16 migrate
-rw-r--r--  1 1000 1000  16857 Apr 15 13:16 seeds.rb
drwxr-xr-x  3 root root   4096 Apr 19 14:37 sphinx
-rw-r--r--  1 1000 1000 211837 Apr 15 13:16 structure.sql
drwxr-xr-x  2 1000 1000   4096 Apr 15 13:16 views
root@aeadaa44e7ac:/littlesis# ls -la /littlesis/
```

**Comment by aepyornis** [comment]
This would be referring to the owner of the postgres database. You are using docker compose correct? if so you can use `bin/littlesis rails db:reset` instead of `bin/rails`. Using `bin/littlesis` should execute the correct docker command: `docker compose -e RAILS_ENV=development app /littlesis/bin/rails db:reset`

**Comment by domguard** [comment]
thanks for the support ziggy
...It's still complaining about PG db owner 
(my shell prompt shows mac mini but I'm running debian)

```shell
mini@mac:~$ littlesis rails db:reset
[+] Running 2/0
 ✔ Container littlesis-rails-postgres-1  Running                                                                               0.0s 
 ✔ Container littlesis-rails-redis-1     Running                                                                               0.0s 
PG::InsufficientPrivilege: ERROR:  must be owner of database littlesis
Couldn't drop database 'littlesis'
rails aborted!
ActiveRecord::StatementInvalid: PG::InsufficientPrivilege: ERROR:  must be owner of database littlesis
/littlesis/bin/rails:4:in `<main>'

Caused by:
PG::InsufficientPrivilege: ERROR:  must be owner of database littlesis
/littlesis/bin/rails:4:in `<main>'
Tasks: TOP => db:drop:_unsafe
(See full trace by running task with --trace)
``` 
Maybe it's the new version of docker compose but the full command did not execute 

```shell
mini@mac:~$ docker compose -e RAILS_ENV=development app /littlesis/bin/rails db:reset
unknown shorthand flag: 'e' in -e
mini@mac:~$ docker compose exec RAILS_ENV=development app /littlesis/bin/rails db:reset
no configuration file provided: not found
```

**Comment by domguard** [comment]
I tried everything from start
Now I have an error when lauching the last command 

`littlesis script create_development_users.rb`

In the postgres container log it says :
```
2023-05-22 20:04:36.663 GMT [1341] ERROR:  relation "users" does not exist at character 491
2023-05-22 20:06:46.213 GMT [1444] FATAL:  role "root" does not exist
2023-05-22 20:04:36.663 GMT [1341] STATEMENT:  SELECT a.attname, format_type(a.atttypid, a.atttypmod),
	       pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
	       c.collname, col_description(a.attrelid, a.attnum) AS comment,
	       attgenerated as attgenerated
	  FROM pg_attribute a
	  LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
	  LEFT JOIN pg_type t ON a.atttypid = t.oid
	  LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
	 WHERE a.attrelid = '"users"'::regclass
	   AND a.attnum > 0 AND NOT a.attisdropped
	 ORDER BY a.attnum
```
And I have unlimited lines saying 

```
2023-05-22 20:04:45.358 GMT [1350] FATAL:  role "root" does not exist
2023-05-22 20:04:56.116 GMT [1359] FATAL:  role "root" does not exist
2023-05-22 20:05:06.921 GMT [1366] FATAL:  role "root" does not exist
2023-05-22 20:05:18.120 GMT [1375] FATAL:  role "root" does not exist
2023-05-22 20:05:29.640 GMT [1383] FATAL:  role "root" does not exist
2023-05-22 20:05:40.993 GMT [1392] FATAL:  role "root" does not exist
2023-05-22 20:05:51.798 GMT [1401] FATAL:  role "root" does not exist
2023-05-22 20:06:02.573 GMT [1410] FATAL:  role "root" does not exist
2023-05-22 20:06:13.551 GMT [1419] FATAL:  role "root" does not exist
2023-05-22 20:06:24.551 GMT [1427] FATAL:  role "root" does not exist
```
